ssh_authorized_keys:
- github:ionstormato
write_files:
- path: /var/lib/connman/default.config
  content: |-
    [service_eth0]
    Type=ethernet
    IPv4=192.168.200.2/255.255.255.0/192.168.200.1
    IPv6=off
    Nameservers=192.168.200.1
hostname: myhost
init_cmd:
- "echo hello, init command"
boot_cmd:
- "echo hello, boot command"
run_cmd:
- "echo hello, run command"

k3os:
  data_sources:
  - cdrom
  modules:
  - kvm
  - nvme
  dns_nameservers:
  - 8.8.8.8
  - 1.1.1.1
  ntp_servers:
  - 0.us.pool.ntp.org
  - 1.us.pool.ntp.org
  k3s_args:
  - server
  - "--disable-agent"
